fix: get_queryset sends self in fields.py which it shouldnt
strawberry-graphql/strawberry-graphql-django pull request #188
Opened 2022-10-08 00:47 UTC by deshk04

details of the issue can be found at https://github.com/strawberry-graphql/strawberry-graphql-django/issues/187 test cases are also update

## Description

Details for the issue can be found at https://github.com/strawberry-graphql/strawberry-graphql-django/issues/187

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

https://github.com/strawberry-graphql/strawberry-graphql-django/issues/187

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-10-08 14:58 UTC, bellini666 requested changes
Just a couple of fixes to the documentation and this should be good to merge :)

2022-10-08 14:58 UTC, bellini666 commented on tests/test_pagination.py
>      def get_queryset(self, queryset, info, **kwargs):
```suggestion
    def get_queryset(cls, queryset, info, **kwargs):
```

2022-10-08 14:58 UTC, bellini666 commented on tests/test_queries.py
>      def get_queryset(self, queryset, info):
```suggestion
    def get_queryset(cls, queryset, info):
```

2022-10-08 14:58 UTC, bellini666 commented on tests/test_queries.py
>      def get_queryset(self, queryset, info):
```suggestion
    def get_queryset(cls, queryset, info):
```

2022-10-10 13:20 UTC, bellini666 approved these changes
Thank you!

2022-10-10 13:30 UTC, merged

2022-10-18 23:37 UTC, fireteam99 commented
Opened a PR to update the documentation regarding this change: https://github.com/strawberry-graphql/strawberry-graphql-django/pull/199