Use getattr, some str fields have choices=None.
strawberry-graphql/strawberry-graphql-django pull request #286
Opened 2023-07-07 23:34 UTC by pcraciunoiu

## Description

It seems that `GENERATE_ENUMS_FROM_CHOICES` breaks `strawberry.auto` types with this error:

```
TypeError: DjangoModelStrawberryType fields cannot be resolved. 'NoneType' object is not iterable
```

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-07-07 23:35 UTC, pcraciunoiu commented on strawberry_django/fields/types.py
> +        and getattr(model_field, "choices", None)
In my testing I found that `model_field.choices` was set to `None` even for `CharField`

2023-07-08 14:54 UTC, bellini666 commented
@pcraciunoiu nice! :)

I just noticed that we don't have a test for this, and that's probably the reason this slipped during the merge.

Could you add a test for it just to make sure it doesn't break again in the future?

2023-07-08 16:02 UTC, bellini666 requested changes
Looks great!

Just need to fix the linting stuff that broke from `pre-commit`

2023-07-08 16:02 UTC, pcraciunoiu commented
> Looks great!
> 
> Just need to fix the linting stuff that broke from `pre-commit`

Sync! Pushed just now

2023-07-08 16:05 UTC, bellini666 approved these changes

2023-07-08 16:06 UTC, merged