Caching Extensions using Django Cache
strawberry-graphql/strawberry-graphql-django pull request #93
Opened 2022-02-24 21:07 UTC by hiporox

Implementations of Strawberry's `[ParserCache](https://strawberry.rocks/docs/extensions/parser-cache#parsercache)` and `[ValidationCache](https://strawberry.rocks/docs/extensions/validation-cache#validationcache)`, but using Django's cache instead of the `functools.lru_cache`

This is blocked by upgrading `strawberry-graphql` to `>=0.98.0`, since that will get us access to `graphql-core@3.2.0`, which fixes this issue https://github.com/graphql-python/graphql-core/issues/112 which stops unpickling `DocumentNode`

2022-03-06 23:51 UTC, bellini666 commented
Hey @hiporox .

I can see how the validation extension being cached using django's cache would be useful, but I wonder in which scenario the parsing would would be? It seems to me that parsing should be faster than requesting an external resource for it (unless it is a very complicated query?)

2022-03-07 18:00 UTC, hiporox commented
@bellini666 I just copied over the functionality of the two types of caches that base strawberry already supports. It is very possible that the parsing cache will just be slower. I have not tested the speed of it in comparison to a regular query lookup. I am very happy to drop that chunk of the code and just leave the validation cache

2022-03-13 13:34 UTC, bellini666 commented
> @bellini666 I just copied over the functionality of the two types of caches that base strawberry already supports. It is very possible that the parsing cache will just be slower. I have not tested the speed of it in comparison to a regular query lookup. I am very happy to drop that chunk of the code and just leave the validation cache

Yeah, I think it is better to only have the validation cache here :)

2022-03-15 20:47 UTC, hiporox commented
@bellini666 Removed the parser cache and fixed the tests. How does it look now?

2022-03-20 16:05 UTC, bellini666 requested changes
Just a few typing issues and it is good to merge! :)

2022-03-23 01:38 UTC, bellini666 requested changes
Just 2 minor details missing

2022-03-23 01:38 UTC, bellini666 commented on strawberry_django/extensions/django_cache_base.py
> +    `timeout: Optional[int | float]`
int is also a valid float, no need to use the union here

```suggestion
    `timeout: Optional[float]`
```

2022-03-23 01:38 UTC, bellini666 commented on strawberry_django/extensions/django_cache_base.py
> +        timeout: Optional[Union[int, float]] = None,
```suggestion
        timeout: Optional[float] = None,
```

2022-03-26 01:48 UTC, bellini666 commented
@hiporox the PR is fine, just need to make the tests pass and I'll merge it!

2022-04-06 20:26 UTC, hiporox commented
@bellini666 Tests pass now, not sure what is up with precommit

2022-04-07 03:50 UTC, bellini666 commented
Thanks for the contribution @hiporox :)

2022-04-07 03:50 UTC, merged